# Generated by Django 3.2.9 on 2025-04-11 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='序号')),
                ('name', models.CharField(default='', max_length=255, verbose_name='标题')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否被删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_http', models.BooleanField(default=False, verbose_name='是否为外链')),
                ('position', models.IntegerField(choices=[(0, 'Header'), (1, 'Footer')], default=0, verbose_name='导航位置')),
                ('link', models.CharField(max_length=255, verbose_name='链接')),
            ],
            options={
                'verbose_name': '导航菜单',
                'verbose_name_plural': '导航菜单',
                'db_table': 'ec_nav',
            },
        ),
    ]
