# Generated by Django 3.2.9 on 2025-04-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='序号')),
                ('name', models.CharField(default='', max_length=255, verbose_name='标题')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否被删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('image', models.ImageField(upload_to='banner/%y/', verbose_name='banner图片地址')),
                ('link', models.CharField(max_length=255, verbose_name='链接')),
                ('note', models.CharField(max_length=255, verbose_name='备注')),
                ('is_http', models.BooleanField(default=False, help_text='站外链接地址', verbose_name='是否为外链')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
                'db_table': 'ec_banner',
            },
        ),
    ]
