# Generated by Django 3.2.9 on 2025-04-30 07:23

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_mobile_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='avatar/%y', verbose_name='头像'),
        ),
    ]
