# Generated by Django 3.2.9 on 2025-05-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20250430_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.SmallIntegerField(choices=[(0, '实战课程'), (1, '会员专享'), (2, '学位课程')], default=0, verbose_name='付费类型'),
        ),
    ]
